version: '3.9'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
    volumes:
      - uploads:/usr/src/app/uploads
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789**Mm"
      POSTGRES_DB: E-commerce
      PORT: 80
      SESSION_SECRET: "${SESSION_SECRET}"
      ADMIN_EMAIL: "test@test.local"
      ADMIN_PASSWORD: "test1234"
    command: npm run start:prod
    ports:
      - "80:80"
    networks:
      - default
    links:
      - database
      - redis
  database:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456789**Mm"
      POSTGRES_DB: E-commerce
  redis:
    image: redis:7-alpine

volumes:
  postgres:
  uploads:
